# Generated by Django 3.2 on 2021-04-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_alter_profile_neighbouhood_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighbouhood_image',
            new_name='neighbourhood_image',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighbouhood_location',
            new_name='neighbourhood_location',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighbouhood_name',
            new_name='neighbourhood_name',
        ),
    ]
