# Generated by Django 3.2 on 2021-04-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_auto_20210413_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpeg', null=True, upload_to='profile'),
        ),
    ]
