# Generated by Django 3.2 on 2021-04-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_image', models.ImageField(upload_to='health/')),
                ('facility_name', models.CharField(max_length=90)),
                ('facility_location', models.CharField(max_length=90)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='neighbour.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=90)),
                ('authority_location', models.CharField(max_length=90)),
                ('authority_image', models.ImageField(upload_to='authority/')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority', to='neighbour.neighbourhood')),
            ],
        ),
    ]
